### ISSUE TITLE
Sync .tag files

### ISSUE THREAD

**Issue by cattermo** [gavoja/aemsync#21]
Hi!
Is there any chance the code could make .tag files sync? 
I have not enough knowledge about them to know if it's possible to build.

/Clara

**Comment by gavoja** [comment]
This should now work properly in 2.0.0. Can you please verify?

**Comment by cattermo** [comment]
I have switched teams so I'll have to check with my former colleges if they can try it out. Will perhaps take a couple of days.

**Comment by cattermo** [comment]
The sync seems to do the right thing, we can see the updated version of the .tag file in CRX. Sadly enough this is not reflected on the webpage which still shows the old version. It seems like the compiled jsp is saved with the old version of the .tag file and not regenerated. Only when the jsp that uses the .tag file is updated the change in the .tag file can be seen on the webpage. I don't know if this could ever be fixed in aemsync.

**Comment by gavoja** [comment]
Thank you for verifying.

To handle your case the aemsync would have to be aware of all the tag usages and push the corresponding jsps accordingly. Given that I switched to HTL in all of my projects, I do not plan to add in such feature. I may however add a plugin system at some point.
